# Generated by Django 4.2 on 2024-09-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_showdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
