# Generated by Django 4.2 on 2024-09-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0002_movie_movie_showdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_status',
            field=models.BooleanField(default=False),
        ),
    ]
