# Generated by Django 4.2 on 2024-09-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0003_movie_movie_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seatname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatplace', models.CharField(max_length=255)),
                ('seatstatus', models.BooleanField(default=False)),
                ('moviename', models.CharField(max_length=255)),
                ('seatstatus_completed', models.BooleanField(default=False)),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='mymovie.movie')),
            ],
        ),
    ]
