# Generated by Django 4.2 on 2024-09-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0004_seatname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticketprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketcost', models.IntegerField(null=True)),
                ('moviename', models.CharField(max_length=255)),
                ('ticketmovie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketmovies', to='mymovie.movie')),
            ],
        ),
    ]
