# Generated by Django 4.2 on 2024-09-26 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0005_ticketprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('moviename', models.CharField(max_length=255)),
                ('seatplace', models.CharField(max_length=255)),
                ('customer_id_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_cost', models.IntegerField(default=0)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('moneystatus_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('customermovie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customermovies', to='mymovie.movie')),
            ],
        ),
    ]
