# Generated by Django 4.2 on 2024-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cusmovie_showdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
